name: Setup Database

on:
  push:
    branches: ["main"]

jobs:
  setup-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2.0.2

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        id: plan
        run: terraform plan -no-color

      - name: Import DB Subnet Group if exists or continue
        id: import_db_subnet
        continue-on-error: true
        run: |
          if aws rds describe-db-subnet-groups --db-subnet-group-name "db-subnet" &>/dev/null; then
            terraform import aws_db_subnet_group.db_subnet db-subnet
          else
            echo "DB Subnet Group does not exist, will be created."
          fi

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
        id: apply
        run: terraform apply -auto-approve
